name: mno_shared
description: Contains the definitions of the custom types (model) used across the Readium-2 Dart projects.
version: 0.1.3
homepage: https://github.com/Mantano/mno_shared_dart
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: 3.3.7
  collection: ^1.17.2
  crypto: ^3.0.3
  dartx: ^1.1.0
  dfunc: ^0.9.0
  equatable: ^2.0.5
  fimber: ^0.6.6
  http: ^0.13.6
  image: ^4.0.17
  intl: ^0.18.1
  meta: ^1.9.1
  dartz: ^0.10.1
  universal_io: ^2.2.1
  xml: ^6.3.0
  mno_commons:
    path: ../commons
  path: ^1.8.3

dev_dependencies:
  image_compare:
    git:
      url: https://github.com/838/image_compare
      ref: upgrade/deps
  lints: ^2.1.0
  test: ^1.24.3

